name: kbv_bar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # A safer and more compatible SDK range

dependencies:
  flutter:
    sdk: flutter

  # Core packages for Firebase and state management
  firebase_core: ^2.27.1
  cloud_firestore: ^4.17.3
  provider: ^6.1.2

  # THE FIX IS HERE: Updated to the latest stable version for modern charts
  fl_chart: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # THE FIX IS HERE: Moved to dev_dependencies as it's a development tool
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Bahnschrift
      # IMPORTANT: Ensure the filename here EXACTLY matches the file in your assets/fonts folder (case-sensitive)
      fonts:
        - asset: assets/fonts/BAHNSCHRIFT.TTF

# Configuration for the launcher icons package
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/images/SBLogo.png"

